"""create initial tables

Revision ID: dbd4907627f8
Revises: 
Create Date: 2026-05-11 08:12:26.066639
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'dbd4907627f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=15), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa', name='uq_vehiculos_placa')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha_cita', sa.Date(), nullable=False),
    sa.Column('hora_cita', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('RESERVADA', 'EN_ATENCION', 'FINALIZADA', 'CANCELADA', name='estado_cita'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'YAPE', 'PLIN', 'TARJETA', name='metodo_pago'), nullable=False),
    sa.Column('estado_pago', sa.Enum('PENDIENTE', 'PAGADO', name='estado_pago'), nullable=False),
    sa.Column('codigo_operacion', sa.String(length=60), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
